### ISSUE TITLE
Relation of this repository with https://github.com/bionanoimaging/View5D

### ISSUE THREAD

**Issue by imagejan** [fiji/View5D#3]
@ctrueden what's the policy of this repository with regard to https://github.com/bionanoimaging/View5D?

Do you regularly (automatically) sync changes? I guess `fiji/View5D` is used to build the maven artifacts hosted on maven.scijava.org and included in the official Fiji downloads?

I'm asking because I noticed that @RainerHeintzmann pushed some changes to https://github.com/bionanoimaging/View5D recently 🙂

**Comment by ctrueden** [comment]
As of today, @RainerHeintzmann and I have unified the View5D code and release process to use https://github.com/bionanoimaging/View5D exclusively. :tada: I will be archiving this repository momentarily.
